apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-app
  
spec:
  selector:
    matchLabels:
      app: exchange-app
  template:
    metadata:
      labels:
        app: exchange-app
    spec:
      containers:
      - name: currency-exchange-app
        image: microservice/learning-crrexchange
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
